export default [
  {
    id: "home",
    title: "Trang chủ",
    titleI18n: "MENU:home",
    to: "/",
    submenu: [],
  },
  {
    id: "introduce",
    title: "Giới thiệu",
    titleI18n: "MENU:introduce",
    to: "/introduce",
    submenu: [],
  },
  {
    id: "teachers",
    title: "Đội ngũ giáo viên",
    titleI18n: "MENU:teachers",
    to: "/teachers",
    submenu: [],
  },
  {
    id: "rate-aso",
    title: "Hướng dẫn đánh giá",
    titleI18n: "MENU:rate-aso",
    to: "/danhgia5sao",
    submenu: [],
  },
  {
    id: "news",
    title: "Tin tức",
    titleI18n: "MENU:news",
    to: "/news",
    submenu: [],
  },
  {
    id: "helper",
    title: "Chính sách",
    titleI18n: "MENU:helper",
    submenu: [
      {
        id: "buy-guide",
        title: "Hướng dẫn mua hàng",
        titleI18n: "MENU:buy-guide",
        to: "/help/buy-guide",
        submenu: [],
      },
      {
        id: "payment-term",
        title: "Điều khoản thanh toán",
        titleI18n: "MENU:payment-term",
        to: "/help/payment-term",
        submenu: [],
      },
      {
        id: "private-policy",
        title: "Chính sách bảo mật",
        titleI18n: "MENU:private-policy",
        to: "/help/private-policy",
        submenu: [],
      },
      {
        id: "complain-policy",
        title: "Chính sách khiếu nại",
        titleI18n: "MENU:complain-policy",
        to: "/help/complain-policy",
        submenu: [],
      },
      {
        id: "return-policy",
        title: "Chính sách hoàn trả",
        titleI18n: "MENU:return-policy",
        to: "/help/return-policy",
        submenu: [],
      },
      {
        id: "license",
        title: "Giấy phép đào tạo",
        titleI18n: "MENU:license",
        to: "/help/license",
        submenu: [],
      },
    ],
  },
  {
    id: "support",
    title: "Hỗ trợ",
    titleI18n: "MENU:support",
    to: "/support",
    submenu: [],
  },
  {
    id: "contact",
    title: "Liên hệ",
    titleI18n: "MENU:contact",
    to: "/contact",
    submenu: [],
  },
];
