export default [
  // {
  //   id: "home",
  //   title: "Trang chủ",
  //   titleI18n: "MENU:home",
  //   to: "/",
  //   submenu: [],
  // },
  {
    id: "products",
    title: "Danh sách sản phẩm",
    titleI18n: "MENU:products",
    to: "/manage-products",
    submenu: [],
  },
  {
    id: "order",
    title: "Quản lí đơn hàng",
    titleI18n: "MENU:order",
    to: "/manage-order",
    submenu: [],
  },
  {
    id: "news",
    title: "Quản lí tin tức",
    titleI18n: "MENU:news",
    to: "/manage-news",
    submenu: [],
  },
  // {
  //   id: "vouchers",
  //   title: "Danh sách khuyến mãi",
  //   titleI18n: "MENU:voucher",
  //   to: "/manage-voucher",
  //   submenu: [],
  // },
  // {
  //   id: "others",
  //   title: "Khác",
  //   titleI18n: "MENU:others",
  //   to: "/others",
  //   submenu: [],
  // },
  // {
  //   id: "helper",
  //   title: "Chính sách",
  //   titleI18n: "MENU:helper",
  //   submenu: [
  //     {
  //       id: "buy-guide",
  //       title: "Hướng dẫn mua hàng",
  //       titleI18n: "MENU:buy-guide",
  //       to: "/help/buy-guide",
  //       submenu: [],
  //     },
  //     {
  //       id: "payment-term",
  //       title: "Điều khoản thanh toán",
  //       titleI18n: "MENU:payment-term",
  //       to: "/help/payment-term",
  //       submenu: [],
  //     },
  //     {
  //       id: "private-policy",
  //       title: "Chính sách bảo mật",
  //       titleI18n: "MENU:private-policy",
  //       to: "/help/private-policy",
  //       submenu: [],
  //     },
  //     {
  //       id: "complain-policy",
  //       title: "Chính sách khiếu nại",
  //       titleI18n: "MENU:complain-policy",
  //       to: "/help/complain-policy",
  //       submenu: [],
  //     },
  //     {
  //       id: "return-policy",
  //       title: "Chính sách hoàn trả",
  //       titleI18n: "MENU:return-policy",
  //       to: "/help/return-policy",
  //       submenu: [],
  //     },
  //     {
  //       id: "license",
  //       title: "Giấy phép đào tạo",
  //       titleI18n: "MENU:license",
  //       to: "/help/license",
  //       submenu: [],
  //     },
  //   ],
  // },
];
